YugaV39 || Changes made for yuga classifier
messai-engineering/Yuga pull request #56
Opened 2022-08-25 14:56 UTC by sonali1404

2022-08-26 06:17 UTC, vizsatiz requested changes

2022-08-29 04:57 UTC, sonali1404 commented on pom.xml
> +            <groupId>com.vaadin.external.google</groupId>
Removed it as I also didn't find any use.

2022-08-29 04:57 UTC, sonali1404 commented on src/main/java/com/twelfthmile/yuga/types/Trie.java
> +        String[] arr = {"airtel", "airtelpaymentsbank", "albk", "allahabadbank", "allbank", "andb", "apb", "apl", "axis", "axisb", "axisbank",
Done.

2022-08-29 04:58 UTC, sonali1404 commented on src/main/java/com/twelfthmile/yuga/types/Trie.java
> +        String[] arr = {"rs", "inr", "cny", "amt", "amount", "ngn", "usd", "cad", "eur", "gbp", "aed", "jpy", "aud", "s$", "lkr", "ksh", "egp"};
Done

2022-08-29 04:58 UTC, sonali1404 commented on src/main/java/com/twelfthmile/yuga/types/Pair.java
> +    B b;
Done

2022-08-29 04:58 UTC, sonali1404 commented on src/main/java/com/twelfthmile/yuga/types/Trie.java
> +        String[] arr = {"6e", "indigo", "ai", "airindia", "sg", "spicejet", "g8", "goair", "uk", "vistara", "ix",
Done

2022-08-29 12:11 UTC, vizsatiz approved these changes

2022-08-29 13:17 UTC, merged